<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Mobile Rush - Bot Discord Project</title>
        <link rel="icon" type="image/x-icon" href="../../project_rush/public/assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="../../project_rush/public/css/styles.css" rel="stylesheet" />
        <link href="../../project_rush/public/css/style.css" rel="stylesheet" />
    </head>
    <body id="page-top">

        <?php include 'nav.html' ?>
        <?php include 'header.html' ?>

        <main>
            <?php include $page ?>
        </main>

        <?php include 'footer.html' ?>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="../../project_rush/public/js/script.js"></script>
    </body>
</html>