<section id="stats">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Infos joueur <?php if(isset($idPlayer)){echo $infosPlayer[0]['pseudo'];}?></h1>
                <?php 
                

                if(isset($idPlayer)){

                    foreach ($infosPlayer[0] as $key => $value) {
                        echo '<p>'.ucfirst($key).' = '.$value.'</p>';
                    }
                    echo '<h5>Rushs joués :</h5>';
                    foreach ($infosPlayerRush as $key => $value) {
                        echo '<p>Jeu : '.$value['name'].', Place : '.$value['place'].', Score : '.$value['score'].'</p>';
                    }
                }

                else{
                    if(isset($idSearch)){
                        echo '<meta http-equiv="refresh" content="0;url=https://www.gremory.fr/project_rush/info/'.$idSearch.'">';
                        //header('Location : https://www.gremory.fr/project_rush/info/'.$idSearch);
                    }
                    else if(isset($regexNo)){
                        echo "L'ID inscrite n'est pas valide.";
                    }
                    else{
                    echo '
                        <form action="/project_rush/info" method="get">
                            <label for="player-search">Rechercher un joueur par ID:</label>
                            <input type="search" id="player-search" name="player-search" placeholder="ID joueur">
                            <input type="submit" name="search" value="Go">
                        </form>
                        ';
                    }
                }

                    
                ?>
            </div>
        </div>
    </div>
</section>