<section id="stats">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Stats</h1>
                <?php 

                if(isset($idPlayer)){

                    echo 'STATS JOEUURS';
                    var_dump($infosPlayer);

                }
                else{

                    echo 'RECHERCHE JOUEUR';

                }

                    
                ?>
            </div>
        </div>
    </div>
</section>