<section id="podium">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Podium (top 10)</h1>
                <div class="wrapper">
                    <h5 class="grid-row0 grid-column1">Place</h5>
                    <h5 class="grid-row0 grid-column2">Pseudo</h5>
                    <h5 class="grid-row0 grid-column3">Lvl</h5>
                    <h5 class="grid-row0 grid-column4">Xp total</h5>
                    <?php 

                        //Affichage du podium
                        $place = 0;
                        for ($i=0; $i < 10 ; $i++) { 
                            $place = $place+1;
                            echo '<div class="grid-column1">'.$place.'</div>';
                            echo '<a href="info/'.$podium[$i]['id_discord'].'"class="grid-column2">'.$podium[$i]['pseudo'].'</a>';
                            echo '<div class="grid-column3">'.$podium[$i]['lvl'].'</div>';
                            echo '<div class="grid-column4">'.$podium[$i]['xp'].'</div>';
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</section>